version: '3.8'

services:
  server:
    build: ./server
    networks:
      - my_network
    ports:
      - 5000:5000
  client:
    build: ./client
    networks:
      - my_network
    depends_on:
      - server

networks:
  my_network:
    driver: bridge